[build]
  base = "interface"
  command = "CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "14.21.3"
  NPM_VERSION = "6.14.18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
